import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from './components/Footer';
import Filter from './components/Filter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex flex-col items-center justify-center min-h-screen h-full text-zinc-400`}
			>
				{/* <Filter /> */}
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
